package VISTA;

import CONTROLADOR.ClaseConexion;
import MODELO.ClaseCargo;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
 
/**
 *
 * @author PRINCIPAL
 */
public class FrmCargo1 extends javax.swing.JFrame {
    ClaseConexion conn=new ClaseConexion(); // INSTANCIAR LA CLASE CONEXIÓN
    public PreparedStatement sql;  // TRABAJO EN SENTENCIAS DE SQL
    ClaseCargo cargo=new ClaseCargo();// INSTANCIAR LA CLASE CARGO
   

    public FrmCargo1() {
        initComponents();
        this.setBounds(200, 200, 656, 390);
        this.setResizable(false);
        String titulos[]={"CODIGO CARGO","NOMBRE CARGO", "SALARIO" };
        Combodatos.addItem("SELECCIONAR");
        this.llamar_combo_cargos();//Permite cargar el combo con los nombres del cargo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txtcodcargo = new javax.swing.JTextField();
        Txtnomcargo = new javax.swing.JTextField();
        Txtsalcargo = new javax.swing.JTextField();
        Bttguardar = new javax.swing.JButton();
        Bttbuscar = new javax.swing.JButton();
        Bttmodificar = new javax.swing.JButton();
        Btteliminar = new javax.swing.JButton();
        Bttlimpiar = new javax.swing.JButton();
        Bttsalir = new javax.swing.JButton();
        Bttlistardatos = new javax.swing.JButton();
        Combodatos = new javax.swing.JComboBox();
        TxtNomCargo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame1.setTitle("DATOS CARGOS DE EMPLEADOS");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("CÓDIGO CARGO");
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 0, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("NOMBRE CARGO");
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 0, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("SALARIO");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 0, 70, 30);

        Txtcodcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtcodcargoActionPerformed(evt);
            }
        });
        Txtcodcargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtcodcargoKeyTyped(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Txtcodcargo);
        Txtcodcargo.setBounds(30, 40, 80, 30);

        Txtnomcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnomcargoActionPerformed(evt);
            }
        });
        Txtnomcargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtnomcargoKeyTyped(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Txtnomcargo);
        Txtnomcargo.setBounds(170, 40, 100, 30);

        Txtsalcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtsalcargoActionPerformed(evt);
            }
        });
        Txtsalcargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtsalcargoKeyTyped(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Txtsalcargo);
        Txtsalcargo.setBounds(300, 40, 90, 30);

        Bttguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/guardar02.jpg"))); // NOI18N
        Bttguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttguardarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Bttguardar);
        Bttguardar.setBounds(500, 10, 100, 30);

        Bttbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/buscar02.jpg"))); // NOI18N
        Bttbuscar.setAlignmentY(0.0F);
        Bttbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bttbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttbuscarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Bttbuscar);
        Bttbuscar.setBounds(500, 50, 100, 30);

        Bttmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/modificar02.jpg"))); // NOI18N
        Bttmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttmodificarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Bttmodificar);
        Bttmodificar.setBounds(500, 90, 100, 30);

        Btteliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/borrar02.jpg"))); // NOI18N
        Btteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtteliminarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Btteliminar);
        Btteliminar.setBounds(500, 140, 100, 30);

        Bttlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LIMPIAR.jpg"))); // NOI18N
        Bttlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttlimpiarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Bttlimpiar);
        Bttlimpiar.setBounds(500, 190, 100, 30);

        Bttsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir02.jpg"))); // NOI18N
        Bttsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttsalirActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Bttsalir);
        Bttsalir.setBounds(500, 233, 100, 30);

        Bttlistardatos.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Bttlistardatos.setText("LISTAR DATOS");
        Bttlistardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttlistardatosActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Bttlistardatos);
        Bttlistardatos.setBounds(10, 90, 140, 23);

        Combodatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombodatosActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Combodatos);
        Combodatos.setBounds(170, 90, 110, 22);

        TxtNomCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNomCargoKeyTyped(evt);
            }
        });
        jInternalFrame1.getContentPane().add(TxtNomCargo);
        TxtNomCargo.setBounds(300, 80, 170, 30);

        TbDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TbDatos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TbDatos);

        jInternalFrame1.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 432, 120);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 640, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BttsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttsalirActionPerformed
       System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_BttsalirActionPerformed

    private void BttguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttguardarActionPerformed
      this.guardar();
 
    }//GEN-LAST:event_BttguardarActionPerformed

    private void BttbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttbuscarActionPerformed
       this.buscar();
       Txtcodcargo.setEnabled(false);
       Txtnomcargo.grabFocus();
    }//GEN-LAST:event_BttbuscarActionPerformed

    private void BttmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttmodificarActionPerformed
       this.Modificar();
        // TODO add your handling code here:
    }//GEN-LAST:event_BttmodificarActionPerformed

    private void BtteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtteliminarActionPerformed
     this.eliminar();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtteliminarActionPerformed

    private void BttlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttlimpiarActionPerformed
      this.limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_BttlimpiarActionPerformed

    private void BttlistardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttlistardatosActionPerformed
   
  try {
      //JTABLE ES UNA HERRAMIENTA VISUAL DE JAVA QUE SIRVE PARA PODER DIBUJAR TABLAS, CON SUS RESPECTIVAS FILAS Y COLUMNAS
      //se crea la Tabla
         Object modelodatos[][]= new Object[0][0];
         //array de String's con los títulos de las columnas
         Object titulos[]={"CODIGO CARGO","NOMBRE CARGO", "SALARIO"};
           cargo.llenar_tabla();//metodo de la clase la cual ejecuta la consulta
           ResultSetMetaData rsMd=cargo.rs.getMetaData(); //PERMITE DEVOLVER EL NUMERO DE FILAS Y COLUMNAS
           int numerocolumnas=rsMd.getColumnCount();//Calcula el # dc columnas de la tabla de datos
           //permite cargar la tabla con los elementos o contenido de cada registro y su titulo
           DefaultTableModel modelo=new DefaultTableModel(modelodatos,titulos);
           TbDatos.setModel(modelo);
           // valida que el exista registros para mostar en la tabla de datos
           while(cargo.rs.next()){
            Object [] fila= new Object[numerocolumnas];
            // Creamos los datos para cada uno de los elementos de la tabla
            for(int y=0; y<numerocolumnas;y++){
            fila [y]=cargo.rs.getObject(y+1);
            }
            modelo.addRow(fila);
           }          
       }   
           catch(SQLException ce){
                  System.out.println("Error al  buscar: "+ce.getMessage());
                   
        }     
// TODO add your handling code here:
    }//GEN-LAST:event_BttlistardatosActionPerformed

    private void CombodatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombodatosActionPerformed
        
         if(cargo.datos!=null)
         {
        this.mostrar_nombre_combo();}
        // TODO add your handling code here:
    }//GEN-LAST:event_CombodatosActionPerformed

    private void TxtcodcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtcodcargoActionPerformed
    if(Txtcodcargo.getText().length()==0)
    {
     JOptionPane.showMessageDialog(null, "Ingrese el codigo del cargo");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtcodcargoActionPerformed

    private void TxtnomcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnomcargoActionPerformed
      if(Txtnomcargo.getText().length()==0)
        {
           JOptionPane.showMessageDialog(null, "Ingrese el nombre del cargo");
        }
 
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtnomcargoActionPerformed

    private void TxtsalcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtsalcargoActionPerformed
       if(Txtsalcargo.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Ingrese el salario del cargo");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtsalcargoActionPerformed

    private void TxtnomcargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtnomcargoKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_TxtnomcargoKeyTyped

    private void TxtcodcargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtcodcargoKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtcodcargoKeyTyped

    private void TxtsalcargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtsalcargoKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtsalcargoKeyTyped

    private void TxtNomCargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomCargoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomCargoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCargo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCargo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCargo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCargo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCargo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttbuscar;
    private javax.swing.JButton Btteliminar;
    private javax.swing.JButton Bttguardar;
    private javax.swing.JButton Bttlimpiar;
    private javax.swing.JButton Bttlistardatos;
    private javax.swing.JButton Bttmodificar;
    private javax.swing.JButton Bttsalir;
    private javax.swing.JComboBox Combodatos;
    private javax.swing.JTable TbDatos;
    private javax.swing.JTextField TxtNomCargo;
    private javax.swing.JTextField Txtcodcargo;
    private javax.swing.JTextField Txtnomcargo;
    private javax.swing.JTextField Txtsalcargo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
//Metodo guardar toma los tres elementos de la tabla cargos y los envia a la clase
//estos son tres atributos, código cargo de tipo entero, nombre cargo de tipo cadena o String
// salario del cargo dato de tipo double.
public void guardar()
    {this.validar();
      cargo.Guardar(Integer.parseInt(Txtcodcargo.getText()), 
                                     Txtnomcargo.getText(), 
                    Double.parseDouble(Txtsalcargo.getText()));
      
      JOptionPane.showMessageDialog(null,"DATOS ALMACENADOS CORRECTAMENTE","GUARDAR",JOptionPane.INFORMATION_MESSAGE);
    }

public void buscar()
    {
      try
        {// la busqueda se efectua por el campo Codigo del cargo
          cargo.Buscar(Integer.parseInt(Txtcodcargo.getText()));
          // si la busqueda encontro algún elemento, se mostrara la información:
          // nombre y salario cargo
          if(cargo.datos.next()==true)
            {
            Txtnomcargo.setText(cargo.datos.getString(2));
            Txtsalcargo.setText(cargo.datos.getString(3));
         }
         else
         {
            JOptionPane.showMessageDialog(null,"el registro no existe", "CARGO",  JOptionPane.ERROR_MESSAGE); 
            this.limpiar();
            Txtcodcargo.setText("");
            Txtcodcargo.grabFocus();
         }
        }
         catch(Exception ex)
         {
             //System.out.println("ERROR AL BUSCAR");
         }   
    }

 public void Modificar()
    {
     this.validar();
     cargo.Modificar(Integer.parseInt(Txtcodcargo.getText()),
             Txtnomcargo.getText(),
             Double.parseDouble(Txtsalcargo.getText()));
    
      JOptionPane.showMessageDialog(null,"DATOS MODIFICADOS CORRECTAMENTE","MODIFICAR",JOptionPane.INFORMATION_MESSAGE);
    }

 public void eliminar()
    {
      int  a = JOptionPane.showConfirmDialog(null,"Desea Eliminar los datos?","SISTEMA",0,1);
      if (a==0) 
      { 
        cargo.Eliminar(Integer.parseInt(Txtcodcargo.getText()));
        JOptionPane.showMessageDialog(null,"EL REGISTRO FUE ELIMINADO DE LA TABLA","CARGO", JOptionPane.INFORMATION_MESSAGE);  
        this.limpiar();                       
      }
    }


public void limpiar()
    {
        Txtcodcargo.setText("");
        TxtNomCargo.setText("");
        Txtnomcargo.setText("");
        Txtsalcargo.setText("");
        Txtcodcargo.grabFocus();
        Txtcodcargo.setEnabled(true);
        Txtnomcargo.setEnabled(true);
        Txtsalcargo.setEnabled(true);
     }

public void llamar_combo_cargos(){
 try{
     cargo.listar_combo_cargos();
     while(cargo.datos.next())
     { // Muestra el dato de nombre de cargos es el 2 campo de la tabla
     this.Combodatos.addItem(cargo.datos.getString(2));
     }
 }
catch(Exception es){
    System.out.println("error al cargar"+es.getMessage());
    }
}
// opcional mustra en la caja de texto la selección del combo
public void mostrar_nombre_combo(){  // mostrarlo en la caja de texto
 try{
    cargo.listar_cargo(Combodatos.getSelectedItem().toString());
    
     if(cargo.datos.next()==true)
     {
        TxtNomCargo.setText(cargo.datos.getString(2));
     }
 }
catch(Exception es){
    System.out.println("error al cargar"+es.getMessage());
    }
}

public void validar(){
if(Txtcodcargo.getText().length()==0)
{
 JOptionPane.showMessageDialog(null, "Ingrese el codigo del cargo");
 Txtcodcargo.setText("");
}

if(Txtnomcargo.getText().length()==0)
{
   JOptionPane.showMessageDialog(null, "Ingrese el nombre del cargo");
   Txtnomcargo.setText("");
}
 if(Txtsalcargo.getText().length()==0)
{
   JOptionPane.showMessageDialog(null, "Ingrese el salario del cargo");
   Txtsalcargo.setText("");
}
}
}